-d D:\datos\proyectos\42_Tang_Nano_9k\30_T_Mapper_MSX_nuevas_tang\impl\gwsynthesis\T_Mapper_MSX.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst D:\datos\proyectos\42_Tang_Nano_9k\30_T_Mapper_MSX_nuevas_tang\tang9k.cst
-cfg D:\datos\proyectos\42_Tang_Nano_9k\30_T_Mapper_MSX_nuevas_tang\impl\pnr\device.cfg
-sdc D:\datos\proyectos\42_Tang_Nano_9k\30_T_Mapper_MSX_nuevas_tang\timing.sdc
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 23
